# Generated by Django 4.2.7 on 2024-01-03 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0009_viewcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewcount',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='viewcount',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='news.article', verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='viewcount',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='viewcount',
            name='ip',
            field=models.GenericIPAddressField(verbose_name='IP адрес'),
        ),
    ]
