# Generated by Django 4.2.7 on 2024-01-10 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_article_category_alter_comment_article_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
    ]
