# Generated by Django 4.2.7 on 2023-12-29 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('nickname', models.CharField(max_length=100, verbose_name='Никнейм')),
                ('birthdate', models.DateField(blank=True, verbose_name='Дата рождения')),
                ('website', models.URLField(blank=True, verbose_name='Персональный сайт')),
                ('github', models.URLField(blank=True, verbose_name='Github')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('image', models.ImageField(default='default_profile.jpg', upload_to='profile_img', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
