# Generated by Django 4.2.7 on 2023-12-20 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nickname', models.CharField(max_length=100)),
                ('birthdate', models.DateField(null=True, verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=20, verbose_name='Пол')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_img', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.AlterField(
            model_name='account',
            name='acc_image',
            field=models.ImageField(default='default.png', upload_to='acc_images'),
        ),
    ]
