# Generated by Django 4.2.7 on 2024-01-09 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_article_category_alter_comment_article_and_more'),
        ('users', '0003_favoritearticle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritearticle',
            options={'ordering': ['date', 'user'], 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterField(
            model_name='favoritearticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='news.article', verbose_name='Новость'),
        ),
    ]
